name: medfiles
description: Secure, local-first medical file organizer (Android MVP)
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  sqflite: ^2.3.0
  sqflite_sqlcipher: ^2.2.1
  path_provider: ^2.1.1
  cryptography: ^2.5.0
  flutter_secure_storage: ^9.0.0
  local_auth: ^2.1.7
  file_picker: ^6.1.1
  path: ^1.8.3
  uuid: ^4.2.1
  bip39: ^1.0.6
  image: ^4.1.3
  pdf_render: ^1.4.0
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  lints: ^3.0.0

flutter:
  uses-material-design: true
