name: medfiles
description: Secure, local-first medical file organizer (Android MVP)
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  sqflite: ^2.4.2
  sqflite_sqlcipher: ^3.4.0
  path_provider: ^2.1.5
  cryptography: ^2.7.0
  flutter_secure_storage: ^9.2.4
  local_auth: ^3.0.0
  file_picker: ^10.3.3
  path: ^1.9.1
  uuid: ^4.5.1
  image: ^4.5.4
  provider: ^6.1.5+1
  pdfrx: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  lints: ^5.1.1

flutter:
  uses-material-design: true
